# Routinator Configuration File
# For more info: https://routinator.docs.nlnetlabs.nl/en/stable/configuration.html

# The directory where Routinator stores its RPKI data cache
repository-dir = "/data/rpki/repository"

# The interval in seconds between validation runs
refresh = 600

# We don't need a heavy HTTP/RTR server for this sidecar setup, 
# but we can enable it for future-proofing or debugging.
# http-listen = ["0.0.0.0:8080"]

# Ensure we have enough log detail
log-level = "info"
